# Generated by Django 6.0.5 on 2026-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('botao_texto', models.CharField(default='Ver Produtos', max_length=50)),
                ('botao_link', models.CharField(default='/', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
