# Generated by Django 6.0.5 on 2026-05-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='botao_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='botao_texto',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo',
        ),
    ]
