# Generated by Django 6.0.5 on 2026-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
