# Generated by Django 6.0.5 on 2026-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_pedido_cep_pedido_cidade_pedido_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
