# Generated by Django 6.0.5 on 2026-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_pedido_prazo_entrega_pedido_tipo_frete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
