# Generated by Django 6.0.5 on 2026-06-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_altura_produto_comprimento_produto_largura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_frete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo_entrega',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
