# Generated by Django 6.0.5 on 2026-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_pedido_codigo_frete_alter_pedido_prazo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelhorEnvioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
