# Generated by Django 6.0.5 on 2026-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_categoria_destaque_home_produto_destaque_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='destaque_home',
        ),
    ]
