# Generated by Django 6.0.5 on 2026-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_remove_produto_destaque_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaque_home',
            field=models.BooleanField(default=False, verbose_name='Destacar na Home?'),
        ),
    ]
